<a href="https://colab.research.google.com/github/ajit04022000/MACHINE_LEARNING/blob/main/4)Save_model_using_joblib_and_pickel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [13]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/4_save_model/homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [14]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [15]:
model.coef_

array([135.78767123])

In [16]:
model.intercept_

180616.43835616432

In [17]:
model.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

##Save Model To a File Using Python Pickle

In [18]:
import pickle

In [20]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [21]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [22]:
mp.coef_

array([135.78767123])

In [23]:
mp.intercept_

180616.43835616432

In [24]:
mp.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

##Save Trained Model Using joblib

In [28]:
pip install joblib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from sklearn.externals import joblib

In [ ]:
joblib.dump(model, 'model_joblib')

In [ ]:
mj = joblib.load('model_joblib')

In [ ]:
mj.coef_

In [ ]:
mj.intercept_